##
# The MIT License (MIT)
#
# Copyright (c) 2014-2022 <mickael.jeanroy@gmail.com>
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.
##

name: Release

on:
  workflow_dispatch:
    inputs:
      releaseVersion:
        description: "Release version (X.Y.Z)"
        required: true
      developmentVersion:
        description: "Snapshot version (X.Y.Z without -SNAPSHOT suffix)"
        required: true
      dry_run:
        description: Run dry-run release
        required: true
        type: choice
        default: 'true'
        options:
          - 'true'
          - 'false'

jobs:
  release:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5.0.0
      - uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Import GPG Key
        uses: crazy-max/ghaction-import-gpg@v6.2.0
        with:
          gpg_private_key: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
      - name: Set up JDK
        uses: actions/setup-java@v4.7.1
        with:
          java-version: 21
          distribution: 'temurin'
          check-latest: true

          # ID of the distributionManagement repository in the pom.xml file.
          server-id: 'sonatype-nexus-staging'

          # Environment variable name for the username for authentication to the Apache Maven repository.
          server-username: MAVEN_USERNAME

          # Environment variable name for password or token for authentication to the Apache Maven repository.
          server-password: MAVEN_PASSWORD

          # GPG private key to import. Default is empty string.
          gpg-private-key: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}

          # Environment variable name for the GPG private key passphrase.
          gpg-passphrase: GPG_PASSPHRASE
      - name: Configure Git User
        run: |
          git config user.email "mickael.jeanroy@gmail.com"
          git config user.name "Mickael Jeanroy"
      - name: Release
        run: |
          ./mvnw -B -U \
            release:prepare \
            release:perform \
            -DdryRun=${{ inputs.dry_run }} \
            -DreleaseVersion=${{ github.event.inputs.releaseVersion }} \
            -DdevelopmentVersion=${{ github.event.inputs.developmentVersion }}-SNAPSHOT \
        env:
          MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
          GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}